sclorg/mariadb-container

hack/common.mk

Fix inden from #10 
@hhorak @bparees Please merge.

Fix common.mk indent.

---

10.0/Dockerfile.rhel7
10.1/Dockerfile.rhel7

Labels now should follow spec at https://github.com/projectatomic/ContainerApplicationGenericLabels/blob/master/vendor/redhat/labels.md

New labels for OSBS

---

hack/build.sh

Reverts sclorg/mariadb-container#14 @hhorak Please merge.
Passing image ID is not possible for s2i based images (running s2i build in tests fails - using image ID instead of tag is not supported). So this PR (and similar PRs for other container images) should be reverted to keep building scripts same for s2i based and non-s2i based images.
As mentioned in sclorg/postgresql-container#155, different approach could be used, so I will try to prepare something. But it would be helpful to have shared build scripts as mentioned in sclorg/postgresql-container#138.

Revert "Pass image ID for testing"

---

examples/mariadb-ephemeral-template.json
examples/mariadb-persistent-template.json

https://github.com/openshift/origin/pull/17922#discussion_r160709178

templates: omit version/tag 10.0 from description

---

root-common/usr/bin/run-mysqld-slave

Fixes the same issue as: https://github.com/sclorg/mysql-container/issues/226

Reverting the behvior when slave starts with initialized database

---

README.md

URL of OKD is docs.okd.io now

---

examples/mariadb-ephemeral-template.json
examples/mariadb-persistent-template.json
imagestreams/mariadb-rhel7-ppc64le.json

Adding ppc64le based imagestream and examples for mariadb 10.2

adding ppc64le imagestream and examples

---

root-common/usr/bin/run-mysqld-slave
root-common/usr/share/container-scripts/mysql/common.sh

As this option does not depend on name resolutions and filters out link local addresses

run: Use hostname -I

---

.gitignore
test/run
test/run-openshift-local-cluster
test/run-openshift-remote-cluster
test/test-lib-mysql.sh

Fix openshift tests to run correctly locally and in remote cluster as well

---

10.1/Dockerfile
10.1/Dockerfile.fedora
10.1/Dockerfile.rhel7
10.2/Dockerfile
10.2/Dockerfile.fedora
10.2/Dockerfile.rhel7
10.3/Dockerfile.fedora
10.3/Dockerfile.rhel8

As it does not work in Openshift Online for builder images for now.

Do not use VOLUME command in Dockerfiles

---

imagestreams/mariadb-centos7.json
imagestreams/mariadb-rhel7.json

per request from @siamaksade from OpenShift PM, this PR removes EOF version from the imagestream file

remove versions that are EOL

---

test/check_imagestreams.py
test/run

This commit checks the latest version in the imagestreams.

Check the latest version in imagestreams

---

imagestreams/mariadb-rhel-aarch64.json
imagestreams/mariadb-rhel.json

Should be merged once rh-mariadb105 and mariadb:10.5 in RHEL-8 are released.

Add 10.5 imagestream

---

.github/workflows/build-and-push.yml

Add support for build and push mariadb to Quai.io

---

examples/mariadb-ephemeral-template.json
examples/mariadb-persistent-template.json
imagestreams/mariadb-centos.json
imagestreams/mariadb-rhel-aarch64.json
imagestreams/mariadb-rhel.json

- Update OKD imagestream for mariadb-105-centos7
- Use groupified apiVersion

Update OKD imagestream, use groupified apiVersion

---

imagestreams/mariadb-centos.json
test/run-openshift-remote-cluster
test/test-lib-mysql.sh

This pull request updates container-common-scripts.
And fixes OpenShift 3 and OpenShift 4 tests

Fix OpenShift 3 and 4 tests

---

.github/workflows/build-and-push.yml

@phracek 
Sorry, I did not catch this typo in the previous PR.

fix typo in build-and-push

---

.github/workflows/container-tests.yml
README.md

Add support for testing CentOS Stream 8

---

.github/workflows/openshift-tests.yml

This pull request uses Testing Farm as GitHub Action for OpenShift tests.

Support OpenShift tests by Testing Farm as GitHub Action

---

test/test-lib-mysql.sh

Fix OpenShift 4 tests

---

test/test-lib-mysql.sh

Support testing image stream for RHEL9 and testing RHEL9 and 10.5 for template

Support imagestreams RHEL9

---

test/mariadb-persistent-template.json
test/run-openshift-remote-cluster
test/test-lib-mysql.sh

This pull request fixes OpenShift 4 tests

Fix openshift4 tests

---

test/run

tests: make sure that the testsuite ends wit error if any test fails

tests: make sure that the testsuite ends wit error if any test fails

---

imagestreams/mariadb-centos.json

Fix mariadb import url in OKD

---

imagestreams/mariadb-centos.json

cXs imagestreams: use -elX suffix for tag names

---

.github/workflows/openshift-tests.yml
imagestreams/imagestreams.yaml
imagestreams/mariadb-centos.json
imagestreams/mariadb-rhel-aarch64.json
imagestreams/mariadb-rhel.json

imagestreams: mariadb does not have sample repo

---

test/test_mariadb_imagestream.py
test/test_mariadb_imagestream_template.py
test/test_mariadb_latest_imagestreams.py
test/test_mariadb_template.py

Use VERSION insterad of SINGLE_VERSION like we do in whole org

---

.github/workflows/container-tests.yml

This pull request updates container-tests.yml file so we can test CentOS Stream 10 as well.
No more other files are updated.

This pull request enables testing mariadb on CentOS Stream 10

---

test/run

This file will no longer be included in images produced by Konflux, thus we shouldn't test it.

Disable tests depending on help.1 file presence

---

.github/workflows/container-tests.yml
.github/workflows/openshift-pytests.yml
.github/workflows/openshift-tests.yml

This pull request updates GitHub Action file '.yml' file so we can test RHEL 10 as well.
No more other files are updated.

Enables testing mariadb on RHEL 10

---

.github/workflows/container-tests.yml

The current version has been retired

Switch Ubuntu 20.04 to Ubuntu latest. 
