sclorg/mariadb-container

10.0/test/run
10.1/test/run

mariadb-container and mysql-container contains almost same `test/run` script. So now it is not possible to run mariadb and mysql tests simultaneously (both creates containers `config_test` and `dynamic_config_test`).
This PR fixes this. So test script doesn't create containers with name and it address them by cidfile.
@hhorak @bparees @mnagy Please take a look.

Don't create containers with name during testing

---

10.0/Dockerfile.rhel7
10.1/Dockerfile.rhel7

Enabling host repositories didn't work with docker 1.10 and newer inside OpenStack. It was fixed in latest rhel7 base release, so using 'rhel7' base image is required for RHEL CI. Postgresql PR - sclorg/postgresql-container#150
Also to enable repositories inside container running 'yum' first is required - see https://access.redhat.com/solutions/1443553 . Similar to sclorg/s2i-base-container#99 .
@hhorak @bparees Please take a look and merge.

Fix using subscription in container

---

hack/build.sh

When running `test/run` use image ID instead of IMAGE_NAME. This allows parallel testing of images (for example parallel testing of PRs in Jenkins).
@hhorak @bparees @praiskup Please take a look. I will prepare PRs for other repos later.

Pass image ID for testing

---

10.1/root/usr/share/container-scripts/mysql/common.sh

This will make the container image working with newest RPMs, so it is a work-around for https://bugzilla.redhat.com/show_bug.cgi?id=1406391
However, we should remove this once the RPMs are fixed.

Using empty --basedir for mysql_install_db 

---

10.1/Dockerfile.fedora

This only demonstrates that we can use the same sources for the container for SCL and Fedora packages. It does not influence any existing sources.

Port dockerfile for fedora and include it as addition

---

10.0/test/run
10.1/test/run

Upgrade from docker 1.10 to docker 1.12 changed format of parsing `docker exec` arguments.
So `docker exec $(get_cid "$id") bash -c mysql <<< "SELECT 1;"` is waiting forever. Quotes or `-i` is required to make test passing.
EDIT: `assert_local_access` test was not working right with docker 1.10. (`mysql` got no input, so it succeded)

Fix tests for docker 1.12 (changed docker exec parsing)

---

10.0/Dockerfile.rhel7
10.0/root/usr/share/container-scripts/mysql/my-tuning.cnf.template
10.1/Dockerfile.rhel7
10.1/root/usr/share/container-scripts/mysql/my-tuning.cnf.template

Do not set `innodb_additional_mem_pool_size` server option which is deprecated and also not used unless `innodb_use_sys_malloc` is turned off, which is not.
See more at https://mariadb.com/kb/en/mariadb/xtradbinnodb-server-system-variables/#innodb_additional_mem_pool_size

Do not set innodb_additional_mem_pool_size which is deprecated

---

10.0/Dockerfile
10.0/Dockerfile.rhel7
10.1/Dockerfile
10.1/Dockerfile.fedora
10.1/Dockerfile.rhel7
10.2/Dockerfile
10.2/Dockerfile.fedora
10.2/Dockerfile.rhel7

https://github.com/projectatomic/ContainerApplicationGenericLabels/blob/master/vendor/redhat/labels.md#other-labels
We're in a process of decommissioning our modular images: https://github.com/container-images/mariadb/pull/3. Since the modular variant is just about `dnf install -y $the_module` I don't think it makes sense to create a dedicated Dockerfile for such thing.

add usage and description labels

---

test/run

Drop the following warning message:
test/run: line 31: warning: command substitution: ignored null byte in
input

Drop -z parameter of readlink to avoid warning message

---

10.0/Dockerfile
10.0/Dockerfile.rhel7
10.0/root/usr/share/container-scripts/mysql/README.md
10.1/Dockerfile
10.1/Dockerfile.fedora
10.1/Dockerfile.rhel7
10.1/root/usr/share/container-scripts/mysql/README.md
10.2/Dockerfile
10.2/Dockerfile.fedora
10.2/Dockerfile.rhel7
10.2/root/usr/share/container-scripts/mysql/README.md
README.md
root-common/usr/bin/usage

Use maintainer label consistently
Few edits in top-level README
Using usage label and command
Remove tables in README, because go-md2man cannot convert them properly

Various small documentation related changes

---

examples/mariadb-ephemeral-template.json
examples/mariadb-persistent-template.json

[Replace 'template.openshift.io' with 'openshift.io'](https://github.com/openshift/origin/pull/17922#pullrequestreview-86819501)
and 
[Remove ' (Persistent)'](https://github.com/openshift/origin/pull/17922#pullrequestreview-86940496)

Fix templates according to `openshift/origin`

---

10.0/root/usr/share/container-scripts/mysql/README.md
10.1/Dockerfile.fedora
10.1/root/usr/share/container-scripts/mysql/README.md
10.2/Dockerfile.fedora
10.2/root/usr/share/container-scripts/mysql/README.md
root-common/usr/bin/run-mysqld
root-common/usr/bin/run-mysqld-master
root-common/usr/bin/run-mysqld-slave
root-common/usr/share/container-scripts/mysql/common.sh
root-common/usr/share/container-scripts/mysql/helpers.sh
root-common/usr/share/container-scripts/mysql/init/40-check-upgrade.sh
root-common/usr/share/container-scripts/mysql/init/40-datadir-action.sh
root-common/usr/share/container-scripts/mysql/pre-init/20-validate-variables.sh
test/run

MySQL and MariaDB use versions that consist of three numbers X.Y.Z (e.g. 5.6.23).
For version changes in Z part, the server's binary data format stays compatible and thus no
special upgrade procedure is needed. For upgrades from X.Y to X.Y+1, consider doing manual
steps as described at
https://mariadb.com/kb/en/library/upgrading-from-mariadb-101-to-mariadb-102/
Skipping versions like from X.Y to X.Y+2 or downgrading to lower version is not supported;
the only exception is ugrading from MariaDB 5.5 to MariaDB 10.0.
**Important**: Upgrading to a new version is always risky and users are expected to make a full
back-up of all data before.
A safer solution to upgrade is to dump all data using `mysqldump` or `mysqldbexport` and then
load the data using `mysql` or `mysqldbimport` into an empty …

Add logic for upgrading datadir

---

10.2/Dockerfile

It is not necessary to use testing repo now anymore, all packages are in released repo already.

Use released repos only

---

root-common/etc/my.cnf

This will fix crashing of the MariaDB image in the OpenShift catalog on init when using GlusterFS as storage backend. 
GlusterFS will mount the volume directly on /var/lib/mysql/data and by default a new volume will have a .trashcan dir. The init scripts of MariaDB will fall over this empty dir with the error : 
`[ERROR] Invalid (old?) table or database name '.trashcan'
mysqlcheck: Got error: 1102: Incorrect database name '#mysql50#.trashcan' when selecting the database
FATAL ERROR: Upgrade failed
`
The ignore-db-dir option can be added multiple times to add on each other.

Fix for datadir on GlusterFS.

---

10.1/Dockerfile.fedora
10.2/Dockerfile.fedora

Remove release label - in Fedora it's updated automatically by build system.
Remove arch label - 'Optional: if omitted, it will be built for
all supported Fedora Architectures'
+ make fedora Dockerfile more similar to other OSes
@pkubatrh Please take a look and merge.

Remove release label

---

10.3/root/usr/share/container-scripts/mysql/README.md

CentOS 8 is not released, so delete links and inform users.
Related to issue #98 .

Fix README for mariadb 10.3

---

imagestreams/mariadb-centos7.json
imagestreams/mariadb-rhel7-ppc64le.json
imagestreams/mariadb-rhel7.json

This pull request removes a minor typo for all the image stream descriptions.

Removing Version Typo from Image Stream Descriptions

---

imagestreams/mariadb-centos7.json
imagestreams/mariadb-rhel7-ppc64le.json
imagestreams/mariadb-rhel7-s390x.json

This was asked by @siamaksade and @gabemontero and consulted more that we should be ok with just one imagestream file and more tags for alternate architectures. Once merged, we'll submit a PR for https://github.com/openshift/library/blob/master/official.yaml and add `arch_ppc64le` and `arch_s390x` tags there.
@siamaksade or @gabemontero, can you take a look and verify we understood each other well and we can continue with other images this way?

Add s390x image stream and add 10.3 version

---

root-common/usr/share/container-scripts/mysql/init/50-passwd-change.sh
test/run

When changing password for a different user, this user is not found in the database, so the container fails with:
```
ERROR 1396 (HY000) at line 1: Operation ALTER USER failed for 'newuser'@'%'
```
or
```
ERROR 1133 (28000) at line 1: Can't find any matching row in the user table
```
The change adds a specific check that the user exists, and the behaviour change is that in case the user does not exist, the container does not fail, only a warning is printed.
This is a same PR as https://github.com/sclorg/mysql-container/pull/269 and should also close #78.

Fixes BZ#1653215 Operation ALTER USER failed

---

imagestreams/mariadb-centos7.json
imagestreams/mariadb-rhel7-ppc64le.json
imagestreams/mariadb-rhel7-s390x.json
imagestreams/mariadb-rhel7.json

Order is now: latest, 10.3 and 10.2.
We would like to test if the latest version is present in the imagestreams.
It is done by ansible-script (https://github.com/sclorg/ansible-tests/pull/4)
The second tag is going to be used for test if version is the latest.

Reorder imagestreams.

---

test/imagestreams
test/run-openshift-local-cluster
test/run-openshift-remote-cluster
test/test-lib-mysql.sh

This PR combines more changes:
- add image stream test
- adopts new functions refactored in https://github.com/sclorg/container-common-scripts/pull/155/files
- enables tests to be run in a remote OCP4 cluster

[WIP] Use refactored functions and enable testing in remote OCP4

---

examples/mariadb-ephemeral-template.json
examples/mariadb-persistent-template.json

When using just TCP ping for the port, mysqld daemon expects some data that do not come. With "set global log_error_verbosity=3;", a warning is printed to the errlog, like this:
Got an error reading communication packets
(every 10s, depending on the liveness probe delay)
This makes issues when tools analyze the errlog, because those innoncent connection errors cannot be distinguised from real connection issues.
With using mysqladmin, similar to the readiness probe, the warning should not be printed any more.
Related: rhbz#1767393
Upstream issue: https://github.com/sclorg/mysql-container/issues/274
Upstream fix: https://github.com/sclorg/mysql-container/pull/285

Use mysqladmin for the liveness probe

---

10.3/Dockerfile
10.3/root/usr/share/container-scripts/mysql/README.md
root-common/usr/share/container-scripts/mysql/common.sh
test/run

like the centos/mariadb (5.5) container does
Question: I see these variables listed in multiple Dockerfile files. Should all of them be updated ?
Any ETA when this could make it into Docker Hub or a reasonable workaround ?

Support MYSQL_CHARSET and MYSQL_COLLATION variables

---

10.3/Dockerfile.fedora

Removed .exclude-fedora to enabled Fedora build. Updated Fedora version from 29 to 31 (still using MariaDB 10.3) and tested using "make test" and real-live deployment on OKD.

Update fedora version

---

10.3/Dockerfile
10.3/root/usr/share/container-scripts/mysql/README.md
README.md

This commit adds support for Quay.io registry instead of Docker.io.
Docker.io introduces rate limit which block tests.

Update README.md and Dockerfile for Quay.io

---

test/run
test/run-openshift-local-cluster
test/test-lib-mysql.sh

Move testing imagestream into openshift tests.
Container-common-scripts are updated into the latest.

Move testing imagestream into openshift tests

---

imagestreams/mariadb-centos.json

Use quay.io as a source of the images to avoid Docker Hub ratelimiting where possible

imagestream: point centos7 images to quay.io

---

imagestreams/mariadb-centos.json

Use quay.io in mariadb-centos imagestream for RHEL7

---

test/run-openshift-remote-cluster
test/test-lib-mysql.sh
test/test-lib-remote-openshift.sh

This pull request adds the possibility to test mariadb-container on OpenShift 4 remote cluster
via the external registry, where is pushed the image after the build.

Support testing on OpenShift-4

---

root-common/etc/my.cnf

also expand ignore-db-dir to ignore-db-dirs otherwise startup complains:
[Note] Using unique option prefix 'ignore-db-dir' is error-prone and can break in the future. Please use the full name 'ignore_db_dirs' instead.

my.cnf: ignore netapp snapshot dir

---

.github/workflows/docker-tests.yml

This pull request adds support for testing mariadb-container in CentOS Stream 9 by Testing Farm.

Support testing mariadb-container in CentOS Stream 9 by Testing Farm

---

examples/mariadb-ephemeral-template.json
examples/mariadb-persistent-template.json

add template icon

---

.github/workflows/build-and-push.yml
10.5/Dockerfile.c9s

This pull request adds support for building, testing, and pushing `mariadb-container` image
to CentOS Stream 9.
Container-common-scripts are updated.
`10.5/Dockerfile.c9s` docker file is added for building `mariadb-container` image for CentOS Stream 9.
`build-and-push.yml` file, as GitHub Action is updated to be able to push image into quay.io/sclorg/mariadb-105-c9s repository.
Dockefile.rhel8 and Dockerfile.c9s difference:
```bash
$ diff 10.5/Dockerfile.rhel8 10.5/Dockerfile.c9s
1c1
< FROM ubi8/s2i-core
---
> FROM quay.io/sclorg/s2i-core-c9s:c9s
29c29
<       name="rhel8/mariadb-105" \
---
>       name="sclorg/mariadb-105-c9s" \
31c31
<       usage="podman run -d -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=db -p 3306:3306 rhel8/mariadb-105" \
---
>       usage="podman run …
```

Support building testing mariadb-container in CentOS Stream 9

---

.github/workflows/build-and-push.yml
10.3/Dockerfile.fedora
10.5/Dockerfile.fedora
README.md
test/run

This pull request builds and pushes mariadb-10.5 container to registry
`quay.io/fedora/mariadb-105`.

Build and push mariadb 10.5 image to quay.io/fedora/mariadb-105

---

test/run-openshift-remote-cluster

Nowadays, we use the external OpenShift registry for the testing image.
OpenShift 4 provides an internal OpenShift registry. Let's use it.

Use internal openshift register

---

10.5/Dockerfile.rhel9
10.5/root/usr/share/container-scripts/mysql/README.md
README.md

This pull request adds support for building, and testing mariadb-container on the RHEL9 host.
It also updates documentation with link to quay.io and RHEL9 info.

Support build and test maridb-container on RHEL9

---

test/examples
test/run-openshift-remote-cluster
test/test-lib-mysql.sh
test/test-openshift.yaml

* container-common-scripts are updated
* Couple fixes in test-lib-mysql.sh and run-remote-openshift script
* add examples and test-openshift.yaml symlinks to test directory

This pull request allows to enable testing mariadb-container into CVP pipeline

---

10.3/Dockerfile.c8s
10.3/Dockerfile.fedora
10.3/Dockerfile.rhel8
10.5/Dockerfile.c8s
10.5/Dockerfile.c9s
10.5/Dockerfile.fedora
10.5/Dockerfile.rhel8
10.5/Dockerfile.rhel9

Otherwise when a wrong stream is installed, it's only found by scl test, which is too late in the process and might even go through uncought, especially when the scl test is removed for non-SCL distros at some point.

Add a test in Dockerfile directly to check the version

---

root-common/usr/share/container-scripts/mysql/common.sh

This option disables creation of the test database and anonymous users This fixes the issue: https://github.com/sclorg/mariadb-container/issues/198

Use --skip-test-db option with mysql_install_db

---

.github/workflows/build-and-push.yml
.github/workflows/container-tests.yml

The CentOS registry has been decommissioned[1]. Alternative registries provide only old versions of CentOS base image. Because there is no known possibility currently to obtain fresh CentOS7 base container image (we do not want to update old images with yum -y update) we are stopping rebuilds of the SCLorg's s2i-images too.  Already built images will be still available on quay.io.
[1] https://lists.centos.org/pipermail/centos-devel/2023-May/142956.html

disable testing and pushing to quay.io for CentOS7 image

---

README.md

MariaDB container in version 10.3 has reached EOL for RHEL7 in June 2023.
Let's stop test it.

MariaDB 10.3 has reached EOL in June 2023

---

imagestreams/mariadb-centos.json

Also switch to using the C8S image from quay.io for EL8 instead of pulling from docker.io, avoiding rate-limits.

imagestreams/mariadb-centos: Update for C9S

---

.github/workflows/container-tests.yml
.github/workflows/openshift-tests.yml

Add support for testing MariaDB 10.11 in sclorg pipeline.
Files that were modified are container-tests.yml and openshift-tests.yml

Add support for testing MariaDB 10.11 in sclorg pipeline.

---

10.11/Dockerfile.c8s
10.11/Dockerfile.c9s
10.11/Dockerfile.fedora
10.11/Dockerfile.rhel8
10.11/Dockerfile.rhel9
10.3/Dockerfile
10.3/Dockerfile.c8s
10.3/Dockerfile.fedora
10.3/Dockerfile.rhel7
10.3/Dockerfile.rhel8
10.5/Dockerfile
10.5/Dockerfile.c8s
10.5/Dockerfile.c9s
10.5/Dockerfile.fedora
10.5/Dockerfile.rhel7
10.5/Dockerfile.rhel8
10.5/Dockerfile.rhel9
s2i-common/bin/run

This pull request removes dead link from this upstream repository.
During the syncing source from upstream/GitLab repositories, the dead links are not sync bu
Testing Farm because security.
Therefore GitLab tests are failing because run script is missing.
Creating symlink in Dockerfile's solved this problem.
Similar pull request is here: https://github.com/sclorg/postgresql-container/pull/552

Do not use dead symlink in repository

---

imagestreams/mariadb-centos.json
imagestreams/mariadb-rhel-aarch64.json
imagestreams/mariadb-rhel.json
test/test-lib-mysql.sh

Fix check for devel image. There should not be postgresql-container but mariadb-container.
Allow check for the latest imagestreams

Add proper latest tag, allow check for latest imagestreams

---

imagestreams/mariadb-centos.json
imagestreams/mariadb-rhel-aarch64.json
imagestreams/mariadb-rhel.json
test/test-lib-mysql.sh

remove imagestreams which are not GA

---

test/run

This will fail until the plugin dir is fixed in the base.cnf file (fix suggested in #235).

Add a test for installing a plugin

---

10.11/Dockerfile.c8s
10.11/Dockerfile.c9s
10.11/Dockerfile.fedora
10.11/Dockerfile.rhel8
10.11/Dockerfile.rhel9
10.5/Dockerfile.c8s
10.5/Dockerfile.c9s
10.5/Dockerfile.fedora
10.5/Dockerfile.rhel7
10.5/Dockerfile.rhel8
10.5/Dockerfile.rhel9

This commit fixes original file /bin/run-mysqld to /usr/bin/run-mysqld.
The file /usr/bin/run-mysqld is copied from directory $VERSION/root-common where it is stored in subdirectory usr/bin/run-mysqld.
The file /bin/run-mysqld does not exist.

This commit fixes original file /bin/run-mysqld to /usr/bin/run-mysqld.

---

imagestreams/imagestreams.yaml
imagestreams/mariadb-centos.json
imagestreams/mariadb-rhel-aarch64.json
imagestreams/mariadb-rhel.json

This pull request adds new imagestreams for RHEL-9.4

Add RHEL-9.4 10.11 imagestreams

---

imagestreams/imagestreams.yaml
imagestreams/mariadb-rhel-aarch64.json
imagestreams/mariadb-rhel.json
test/show_all_imagestreams.py

This pull request only adds show_all_imagestreams.py so it is working.
The file `show_all_imagestreams.py` shows all available imagestreams for this container, that are specified
in the directory `imagestreams`.
The example output will be seen in the next comment.

Add file show_all_imagestreams.py from container-common-scripts

---

.github/workflows/openshift-pytests.yml

This pull request adds support for testing mariadb-container in OpenShift by PyTest suite
https://github.com/sclorg/container-ci-suite

Add GitHub Action for Pytest

---

.github/workflows/openshift-pytests.yml
test/run-openshift-pytest
test/test_mariadb_imagestream.py
test/test_mariadb_imagestream_template.py
test/test_mariadb_latest_imagestreams.py
test/test_mariadb_template.py

This pull request adds support for testing mariadb-container by PyTest.

Add suite for testing mariadb-container in OpenSHift4

---

.github/workflows/container-tests.yml
.github/workflows/openshift-tests.yml
10.3/root/usr/share/container-scripts/mysql/README.md
10.5/root/usr/share/container-scripts/mysql/README.md
README.md
imagestreams/imagestreams.yaml
imagestreams/mariadb-rhel.json
test/run-openshift-remote-cluster
test/test-lib-mysql.sh

This pull request removes RHEL-7 from this repository.

Remove RHEL-7 - EOL in June 2024

---

10.11/Dockerfile.c10s
test/test_mariadb_helm_imagestreams.py
test/test_mariadb_helm_template.py

This pull request adds support for testing Helm Charts stored in https://github.com/sclorg/helm-charts repository

Add testing mariadb Helm Charts in mariadb-container

---

10.11/Dockerfile.c10s
10.11/Dockerfile.rhel10
10.11/root/usr/share/container-scripts/mysql/README.md
README.md

The pull request is separated into two commits.
The first commit adds support for building and testing mariadb-container especially version '10.11' on RHEL10.
The second commit updates README.md file with RHEL10 support.

Add support for building and testing mariadb-container on RHEL10

---

test/test_mariadb_shared_helm_imagestreams.py
test/test_mariadb_shared_helm_template.py

helmcharts. Added suffix 'redhat-'

Fix helm chart tests caused by renaming

---

10.11/Dockerfile.rhel10
test/test_mariadb_imagestream.py
test/test_mariadb_imagestream_template.py
test/test_mariadb_local_template.py
test/test_mariadb_shared_helm_imagestreams.py
test/test_mariadb_shared_helm_template.py

This pull request enables testing mariadb-container on OpenShift 4 shared cluster.

Allow testing mariadb-container on OpenShift 4 shared cluster

---

10.11/Dockerfile.rhel9
10.5/Dockerfile.rhel9

Rename package bind-utils to bind9.18-utils
See Jira Ticket: https://issues.redhat.com/browse/RHEL-80345

Rename package bind-utils to bind9.18-utils

---

10.11/Dockerfile.c10s
10.11/Dockerfile.c9s
10.11/Dockerfile.rhel10
10.11/Dockerfile.rhel9
10.5/Dockerfile.c9s
10.5/Dockerfile.rhel9

[licensing] Add license specification for RHEL and CS images

---

10.11/Dockerfile.fedora
10.11/Dockerfile.rhel10

MariaDB and MySQL package switched to the versioned package layout in Fedora and RHEL 10. The packages can be available in various states, but in all case where a specific version is wanted, specific version must be requested.
Thus container wanting MariaDB 10.11 specifically, must request to install 'mariadb10.11-server' specifically, instead of just 'mariadb-server' which will give you any version that is selected to be the distribution default the current moment.

[build resilience fix] Install DB packages via versioned names

---

10.11/Dockerfile.c10s
10.11/Dockerfile.fedora

The user / group creation process develops. The UID / GID 27 is no longer guaranteed !! With the comming of sysusers.d user creation to Fedora:
https://fedoraproject.org/wiki/Changes/RPMSuportForSystemdSysusers
packages are switching to the new technology.
That brings a wind of change into the MariaDB / MySQL packages in Fedora. Justification for the hardcoded UID / GID 27 does not exist for quite some time. MariaDB upstream use dynamic UID / GID assignment via sysusers.d for nearly a decade now.
The drop of the hardcoded UID / GID 27 in Fedora / RHEL packages may happen. We MUST stop relying on the packages to guarantee the hardcoded value at least from Fedora 42.
For that reasons:
- cherry-pick the user / group creation code from the DB package itself …

[build resilience fix] Begin doing user / group setup ourselves

---

10.11/Dockerfile.c10s
10.11/Dockerfile.c9s
10.11/Dockerfile.fedora
10.11/Dockerfile.rhel10
10.11/Dockerfile.rhel9
10.5/Dockerfile.c9s
10.5/Dockerfile.rhel9

[bugfix] The version must be set in a separate stage, so it can be re-used in the other calls otherwise it's not available when the rest of the ENV block is processed and the ENV values relying on this variable are malformed.
diff of the podman inspect - before the fix and after:
```
"Env": [                                                        "Env": [
...
"MYSQL_VERSION=10.11",                                          "MYSQL_VERSION=10.11",
"MYSQL_SHORT_VERSION=1011",                                     "MYSQL_SHORT_VERSION=1011",
"VERSION=",                               |                     "VERSION=10.11",
"APP_DATA=/opt/app-root/src",                                   "APP_DATA=/opt/app-root/src",
"HOME=/var/lib/mysql", …
```

Fix environment variables

---

10.11/Dockerfile.c10s
10.11/Dockerfile.c9s
10.11/Dockerfile.fedora
10.11/Dockerfile.rhel10
10.11/Dockerfile.rhel9
10.5/Dockerfile.c9s
10.5/Dockerfile.rhel9

Build system without bash fails with:
| Error: resolving step {Value:env Next:0xc0001524d0 Children:[]
| Attributes:map[] Original:ENV MYSQL_SHORT_VERSION=${MYSQL_VERSION//./}
| VERSION=${MYSQL_VERSION}     APP_DATA=/opt/app-root/src     HOME=/var/lib/mysql
| NAME=mariadb     SUMMARY="MariaDB ${MYSQL_VERSION} SQL database server"
| DESCRIPTION="..."
| Flags:[] StartLine:16 EndLine:25}: Missing ':' in substitution: ${MYSQL_VERSION//./}
I tried a lot of ways to work around this, none worked.
Using subshells
- ENV does not support white characters on the right side of assignment Using subshells with scrambled whitepsace characters
- ENV won't invoke the subshell, will treat right side of the assignement as a simple text Using RUN to set $SHELL, trying to use 'export'
- won't be preserved …

[revert] Revert using bash parameter substitution, 'bash' is not guaranteed

---

10.11/Dockerfile.c10s
10.11/Dockerfile.c9s
10.11/Dockerfile.fedora
10.11/Dockerfile.rhel10
10.11/Dockerfile.rhel9
10.5/Dockerfile.c9s
10.5/Dockerfile.rhel9

otherwise it's not available when the rest of the ENV block is processed and the ENV values relying on this variable are malformed.
This commit was mistakenly reverted as a part of revert of a different change

[bugfix] The version must be set in a separate stage, so it can be reused in the other calls

---

.github/workflows/auto-merge-on-demand.yml

It updates container-common-scripts to the latest.
It removes 'auto-merge-on-demand' that run each 45 minutes, but let's call it on request.

Update container common sripts

---

test/test-lib-mysql.sh

Fix expression ${OS%[0-9]*} so it works with rhel10.
But in case of rhel10 it replaces to rhel1 that in templates the file rhel1.yaml does not exist.

Fix expression ${OS%[0-9]*} so it works with rhel10.
